version: '3.6'
services:
  kali:
    container_name: wpscan
    image: kali_wpscan
    build: ./kali/
    tty: true
    restart: on-failure

  wordpress:
    image: wordpress:4.1
    volumes:
     - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    environment:
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME:-wpdb}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
        - 80:80

  mysql:
    image: mysql:5.7
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wpdb
    restart: unless-stopped
    ports:
      - 3306:3306
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8081:80
    container_name: pma
    links:
      - mysql

  wp-config:
    image: wp-config
    build: ./wpcli/
    entrypoint: sh -c "/wait && make -f /scripts/Makefile"
    volumes:
      - ${WORDPRESS_DATA_DIR:-./wordpress}:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - wordpress
      - mysql
    links:
      - mysql
    environment:
      # Waiting for MySQL and wordpress -------------------
      - WAIT_HOSTS=mysql:3306,wordpress:80
      - WAIT_BEFORE_HOSTS=${WAIT_BEFORE_HOSTS:-10}
      - WAIT_AFTER_HOSTS=${WAIT_AFTER_HOSTS:-0}
      - WAIT_HOSTS_TIMEOUT=${WAIT_HOSTS_TIMEOUT:-300}
      - WAIT_SLEEP_INTERVAL=${WAIT_SLEEP_INTERVAL:-30}
      - WAIT_HOST_CONNECT_TIMEOUT=${WAIT_HOST_CONNECT_TIMEOUT:-30}
      # Wordpress configuration -----------------------------
      - WORDPRESS_LOCALE=${WORDPRESS_LOCALE:-fr_FR}
      - WORDPRESS_DB_NAME=${COMPOSE_PROJECT_NAME:-wpdb}
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mysql}
      - WORDPRESS_DB_USER=${DATABASE_USER:-root}
      - WORDPRESS_DB_PASSWORD=${DATABASE_PASSWORD:-password}
      - WORDPRESS_WEBSITE_TITLE=Hello world!
      - WORDPRESS_WEBSITE_URL=${WORDPRESS_WEBSITE_URL:-http://localhost}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER:-wordpress}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD:-\$P\$Bx3MKJ7S2Hshcjnf5dh811pmY5QeAj1}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL:-test@example.com}

